### ISSUE TITLE
How to redefine StoreConfigurable::Object methods

### ISSUE THREAD

**Issue by aaronchi** [metaskills/store_configurable#3]
You mention in the documentation:

```
# Instance methods for +StoreConfigurable::Object+ defined and included in a module so 
# that if you ever wanted to, you could redefine these methods and +super+ up.
```

How would I accomplish this? I want to modify values coming out of the configuration

**Comment by metaskills** [comment]
It would depend on what you are trying to do, can you show me an example?

**Comment by aaronchi** [comment]
I'm trying to interpolate the values coming out as a template with the attributes of the model. It's a really simple function

```
value % self.attributes
```

where value can be something like `this is the record title: %{title}`

but I can't figure out where to override the method and call super to modify the setting value coming out if it's a string.

**Comment by metaskills** [comment]
Hmmm, interesting. Seems you have a few options. The object you are trying to extend is the `DirtyTrackingOrderedOptions` [here](https://github.com/metaskills/store_configurable/blob/master/lib/store_configurable/dirty_options.rb). You could define a `[]` method that would check if the value is a string and then interpolate it under the context of the `__store_configurable_owner__` to which it has a handle to. 

Another way would be to create an instance method under your model that has the store configurable object. Let's say it was a `User` and the template is in `config.plugin.templates.foo`. So you could make an `#template_foo` method that did the work and delegation for you. Or you could make a small class and set of accessors that did this this too. So you would end up with methods like `@user.templates.foo` and it would use the config object. Which seems the more pragmatic choice to me.
