### ISSUE TITLE
Error for any @model.config.import.* property

### ISSUE THREAD

**Issue by laph** [metaskills/store_configurable#7]
It throws a NoMethodError when using any property following this schema: @model.config.import.*

For example you cannot use @model.config.import.a = 23

irb(main):031:0> s.config.import.a = 23
WARNING: DSL method StoreConfigurable::DirtyTrackingOrderedOptions#import called
 at c:/software/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/store_configur
able-3.2.5/lib/store_configurable/object.rb:64:in `method_missing'
NoMethodError: undefined method`a=' for []:Array

**Comment by metaskills** [comment]
I verified this in the test case. The `import` may be one of those reserved on hash that can not be used as a key on the root object. So in this case you have to use the index accessor like so.

``` ruby
@model.config[:import].a = 'b'
@model.save!
@model.reload.config[:import].a # => 'b'
```

I also found out that `import` can be used in one level down too using the dot accessor without the error.

``` ruby
@model.config.namespace.import.a = 'b'
@model.save!
@model.reload.config.namespace.import.a # => 'b'
```
