### ISSUE TITLE
ActiveRecord::SerializationTypeMismatch

### ISSUE THREAD

**Issue by fleetio** [metaskills/store_configurable#9]
I just installed the `store_configurable` gem and followed the migration & model directions, however I'm getting an error when just trying to save a basic `Hash` of data through the Rails console:

``` ruby
user = User.find(1)
user.save
# => true

user.config.something = "something"
user.config
# => {:something=>"something"}

user.save
# => ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Hash, but was a Syck::Omap
```

Is there something I'm missing? I'm using the latest Rails (3.2.13) which I know fixed some YAML serialization vulnerabilities. Shouldn't my little test work?

Thanks for any help!

**Comment by metaskills** [comment]
I know there are issues with Rails 4 in issue #8, but the latest Rails 3.2 should be fine. I just kicked off a build to make sure too. https://travis-ci.org/metaskills/store_configurable/builds/8259641

**Comment by fleetio** [comment]
Thanks. Looks like the tests are passing. Nothing jumps out in the stack trace but there must be something strange about our setup. Will let you know if we figure it out.

Thanks again.

**Comment by fleetio** [comment]
I did some more investigating and can't put a finger on why this isn't working for us. No other gems or anything seem to be conflicting in our setup.

When I debug the `load()` method in `StoreConfigurable::Object::Coding` the `YAML.load(yaml)` call returns a `Syck::Omap` object instead of a `Hash`.

When I do something like:

``` ruby
user.config.works = true
user.config
# => {:works=>true}
```

The `yaml` variable in the `load()` method is set to `"--- !omap  - :works: true "`, which then `YAML.load()` loads as the `Syck::Omap` object, which seems to be the cause of the issue.

Here's more of the stacktrace:

``` ruby
ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Hash, but was a Syck::Omap
    from /Users/tsummerville/.rvm/gems/ruby-1.9.3-p429@fleetio/gems/store_configurable-3.2.5/lib/store_configurable/object.rb:35:in `load'
    from /Users/tsummerville/.rvm/gems/ruby-1.9.3-p429@fleetio/gems/store_configurable-3.2.5/lib/store_configurable/serialization.rb:13:in `unserialize'
    from /Users/tsummerville/.rvm/gems/ruby-1.9.3-p429@fleetio/gems/activerecord-3.2.13/lib/active_record/attribute_methods/serialization.rb:15:in `unserialized_value'
    from /Users/tsummerville/.rvm/gems/ruby-1.9.3-p429@fleetio/gems/activerecord-3.2.13/lib/active_record/attribute_methods/read.rb:72:in `__temp__'
    from /Users/tsummerville/.rvm/gems/ruby-1.9.3-p429@fleetio/gems/store_configurable-3.2.5/lib/store_configurable/read.rb:50:in `_config'
    from /Users/tsummerville/.rvm/gems/ruby-1.9.3-p429@fleetio/gems/store_configurable-3.2.5/lib/store_configurable/read.rb:26:in `config'
    from /Users/tsummerville/.rvm/gems/ruby-1.9.3-p429@fleetio/gems/store_configurable-3.2.5/lib/store_configurable/read.rb:55:in `read_attribute'
    from /Users/tsummerville/.rvm/gems/ruby-1.9.3-p429@fleetio/gems/activerecord-3.2.13/lib/active_record/attribute_methods.rb:260:in `block in arel_attributes_values'
```

Any thoughts as to what might be going on? This seems like such a great Gem and we would love to be able to incorporate it.

Thanks!

**Comment by metaskills** [comment]
Interesting. Digging a little, here is what I found.

```
(kencollins@station) - (~/Repositories/store_configurable) 1.9.3 master_me 
 ∴ bundle console
Resolving dependencies...
>> Syck::Omap
NameError: uninitialized constant Syck::Omap
```

First is that `Syck::Omap` is not initially defined. You have to `require 'syck'` first. I ran the test for the gem by first require'ing syck to see if anything would fail. All green.

I can also see that require'ing it does not change the YAML engine either. 

``` ruby
>> YAML::ENGINE
=> #<YAML::EngineManager:0x007fd3c28d7780 @yamler="psych">
>> require 'syck'
=> true
>> YAML::ENGINE
=> #<YAML::EngineManager:0x007fd3c28d7780 @yamler="psych">
```

Perhaps you are using a different YAML engine?

**Comment by fleetio** [comment]
Aha! Looks like we are using  the "syck" YAML engine: `#<YAML::EngineManager:0x007ff20a83f118 @yamler="syck">`

Looks like `delayed_job` specifies `"syck"` during load (at least the version we're using).

Thanks for digging! This points us in a new direction to try. Will post back what we find.

**Comment by fleetio** [comment]
`delayed_job` was the issue! We were using `v2.1.4` but the made some changes to the YAML serialization in v3. Upgraded, and now `store_configurable` is working like a champ.

Thanks for your help!

**Comment by metaskills** [comment]
Bad ass! Thanks for following up too!
